/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DayOfWeekService } from "../dayOfWeek.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DayOfWeekCreateInput } from "./DayOfWeekCreateInput";
import { DayOfWeek } from "./DayOfWeek";
import { DayOfWeekFindManyArgs } from "./DayOfWeekFindManyArgs";
import { DayOfWeekWhereUniqueInput } from "./DayOfWeekWhereUniqueInput";
import { DayOfWeekUpdateInput } from "./DayOfWeekUpdateInput";
import { ClassModelFindManyArgs } from "../../classModel/base/ClassModelFindManyArgs";
import { ClassModel } from "../../classModel/base/ClassModel";
import { ClassModelWhereUniqueInput } from "../../classModel/base/ClassModelWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DayOfWeekControllerBase {
  constructor(
    protected readonly service: DayOfWeekService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DayOfWeek })
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDayOfWeek(
    @common.Body() data: DayOfWeekCreateInput
  ): Promise<DayOfWeek> {
    return await this.service.createDayOfWeek({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DayOfWeek] })
  @ApiNestedQuery(DayOfWeekFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dayOfWeeks(@common.Req() request: Request): Promise<DayOfWeek[]> {
    const args = plainToClass(DayOfWeekFindManyArgs, request.query);
    return this.service.dayOfWeeks({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DayOfWeek })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dayOfWeek(
    @common.Param() params: DayOfWeekWhereUniqueInput
  ): Promise<DayOfWeek | null> {
    const result = await this.service.dayOfWeek({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DayOfWeek })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDayOfWeek(
    @common.Param() params: DayOfWeekWhereUniqueInput,
    @common.Body() data: DayOfWeekUpdateInput
  ): Promise<DayOfWeek | null> {
    try {
      return await this.service.updateDayOfWeek({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DayOfWeek })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDayOfWeek(
    @common.Param() params: DayOfWeekWhereUniqueInput
  ): Promise<DayOfWeek | null> {
    try {
      return await this.service.deleteDayOfWeek({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/classes")
  @ApiNestedQuery(ClassModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ClassModel",
    action: "read",
    possession: "any",
  })
  async findClasses(
    @common.Req() request: Request,
    @common.Param() params: DayOfWeekWhereUniqueInput
  ): Promise<ClassModel[]> {
    const query = plainToClass(ClassModelFindManyArgs, request.query);
    const results = await this.service.findClasses(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startTime: true,
        endTime: true,

        subject: {
          select: {
            id: true,
          },
        },

        room: {
          select: {
            id: true,
          },
        },

        typeField: true,
        teacher: true,

        subgroup: {
          select: {
            id: true,
          },
        },

        dayOfWeek: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/classes")
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "update",
    possession: "any",
  })
  async connectClasses(
    @common.Param() params: DayOfWeekWhereUniqueInput,
    @common.Body() body: ClassModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      classes: {
        connect: body,
      },
    };
    await this.service.updateDayOfWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/classes")
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "update",
    possession: "any",
  })
  async updateClasses(
    @common.Param() params: DayOfWeekWhereUniqueInput,
    @common.Body() body: ClassModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      classes: {
        set: body,
      },
    };
    await this.service.updateDayOfWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/classes")
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "update",
    possession: "any",
  })
  async disconnectClasses(
    @common.Param() params: DayOfWeekWhereUniqueInput,
    @common.Body() body: ClassModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      classes: {
        disconnect: body,
      },
    };
    await this.service.updateDayOfWeek({
      where: params,
      data,
      select: { id: true },
    });
  }
}
