/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ClassModel } from "./ClassModel";
import { ClassModelCountArgs } from "./ClassModelCountArgs";
import { ClassModelFindManyArgs } from "./ClassModelFindManyArgs";
import { ClassModelFindUniqueArgs } from "./ClassModelFindUniqueArgs";
import { CreateClassModelArgs } from "./CreateClassModelArgs";
import { UpdateClassModelArgs } from "./UpdateClassModelArgs";
import { DeleteClassModelArgs } from "./DeleteClassModelArgs";
import { Subject } from "../../subject/base/Subject";
import { Room } from "../../room/base/Room";
import { Subgroup } from "../../subgroup/base/Subgroup";
import { DayOfWeek } from "../../dayOfWeek/base/DayOfWeek";
import { NewClassCreateInput } from "../NewClassCreateInput";
import { NewClassWhereUniqueInput } from "../NewClassWhereUniqueInput";
import { NewClassUpdateInput } from "../NewClassUpdateInput";
import { ClassModelService } from "../classModel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ClassModel)
export class ClassModelResolverBase {
  constructor(
    protected readonly service: ClassModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ClassModel",
    action: "read",
    possession: "any",
  })
  async _classModelsMeta(
    @graphql.Args() args: ClassModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ClassModel])
  @nestAccessControl.UseRoles({
    resource: "ClassModel",
    action: "read",
    possession: "any",
  })
  async classModels(
    @graphql.Args() args: ClassModelFindManyArgs
  ): Promise<ClassModel[]> {
    return this.service.classModels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ClassModel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ClassModel",
    action: "read",
    possession: "own",
  })
  async classModel(
    @graphql.Args() args: ClassModelFindUniqueArgs
  ): Promise<ClassModel | null> {
    const result = await this.service.classModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ClassModel)
  @nestAccessControl.UseRoles({
    resource: "ClassModel",
    action: "create",
    possession: "any",
  })
  async createClassModel(
    @graphql.Args() args: CreateClassModelArgs
  ): Promise<ClassModel> {
    return await this.service.createClassModel({
      ...args,
      data: {
        ...args.data,

        subject: args.data.subject
          ? {
              connect: args.data.subject,
            }
          : undefined,

        room: args.data.room
          ? {
              connect: args.data.room,
            }
          : undefined,

        subgroup: args.data.subgroup
          ? {
              connect: args.data.subgroup,
            }
          : undefined,

        dayOfWeek: args.data.dayOfWeek
          ? {
              connect: args.data.dayOfWeek,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ClassModel)
  @nestAccessControl.UseRoles({
    resource: "ClassModel",
    action: "update",
    possession: "any",
  })
  async updateClassModel(
    @graphql.Args() args: UpdateClassModelArgs
  ): Promise<ClassModel | null> {
    try {
      return await this.service.updateClassModel({
        ...args,
        data: {
          ...args.data,

          subject: args.data.subject
            ? {
                connect: args.data.subject,
              }
            : undefined,

          room: args.data.room
            ? {
                connect: args.data.room,
              }
            : undefined,

          subgroup: args.data.subgroup
            ? {
                connect: args.data.subgroup,
              }
            : undefined,

          dayOfWeek: args.data.dayOfWeek
            ? {
                connect: args.data.dayOfWeek,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ClassModel)
  @nestAccessControl.UseRoles({
    resource: "ClassModel",
    action: "delete",
    possession: "any",
  })
  async deleteClassModel(
    @graphql.Args() args: DeleteClassModelArgs
  ): Promise<ClassModel | null> {
    try {
      return await this.service.deleteClassModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Subject, {
    nullable: true,
    name: "subject",
  })
  @nestAccessControl.UseRoles({
    resource: "Subject",
    action: "read",
    possession: "any",
  })
  async getSubject(
    @graphql.Parent() parent: ClassModel
  ): Promise<Subject | null> {
    const result = await this.service.getSubject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Room, {
    nullable: true,
    name: "room",
  })
  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "read",
    possession: "any",
  })
  async getRoom(@graphql.Parent() parent: ClassModel): Promise<Room | null> {
    const result = await this.service.getRoom(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Subgroup, {
    nullable: true,
    name: "subgroup",
  })
  @nestAccessControl.UseRoles({
    resource: "Subgroup",
    action: "read",
    possession: "any",
  })
  async getSubgroup(
    @graphql.Parent() parent: ClassModel
  ): Promise<Subgroup | null> {
    const result = await this.service.getSubgroup(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => DayOfWeek, {
    nullable: true,
    name: "dayOfWeek",
  })
  @nestAccessControl.UseRoles({
    resource: "DayOfWeek",
    action: "read",
    possession: "any",
  })
  async getDayOfWeek(
    @graphql.Parent() parent: ClassModel
  ): Promise<DayOfWeek | null> {
    const result = await this.service.getDayOfWeek(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NewClassCreateInput)
  async CreateClass(
    @graphql.Args()
    args: NewClassCreateInput
  ): Promise<NewClassCreateInput> {
    return this.service.CreateClass(args);
  }

  @graphql.Mutation(() => NewClassWhereUniqueInput)
  async DeleteClass(
    @graphql.Args()
    args: NewClassWhereUniqueInput
  ): Promise<NewClassWhereUniqueInput> {
    return this.service.DeleteClass(args);
  }

  @graphql.Mutation(() => NewClassUpdateInput)
  async UpdateClass(
    @graphql.Args()
    args: NewClassUpdateInput
  ): Promise<NewClassUpdateInput> {
    return this.service.UpdateClass(args);
  }
}
