/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { SubjectWhereUniqueInput } from "../../subject/base/SubjectWhereUniqueInput";
import { RoomWhereUniqueInput } from "../../room/base/RoomWhereUniqueInput";
import { SubgroupWhereUniqueInput } from "../../subgroup/base/SubgroupWhereUniqueInput";
import { DayOfWeekWhereUniqueInput } from "../../dayOfWeek/base/DayOfWeekWhereUniqueInput";

@InputType()
class ClassModelUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startTime?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endTime?: Date | null;

  @ApiProperty({
    required: false,
    type: () => SubjectWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SubjectWhereUniqueInput)
  @IsOptional()
  @Field(() => SubjectWhereUniqueInput, {
    nullable: true,
  })
  subject?: SubjectWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => RoomWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RoomWhereUniqueInput)
  @IsOptional()
  @Field(() => RoomWhereUniqueInput, {
    nullable: true,
  })
  room?: RoomWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeField?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  teacher?: string | null;

  @ApiProperty({
    required: false,
    type: () => SubgroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SubgroupWhereUniqueInput)
  @IsOptional()
  @Field(() => SubgroupWhereUniqueInput, {
    nullable: true,
  })
  subgroup?: SubgroupWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DayOfWeekWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DayOfWeekWhereUniqueInput)
  @IsOptional()
  @Field(() => DayOfWeekWhereUniqueInput, {
    nullable: true,
  })
  dayOfWeek?: DayOfWeekWhereUniqueInput | null;
}

export { ClassModelUpdateInput as ClassModelUpdateInput };
