/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BellScheduleService } from "../bellSchedule.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BellScheduleCreateInput } from "./BellScheduleCreateInput";
import { BellSchedule } from "./BellSchedule";
import { BellScheduleFindManyArgs } from "./BellScheduleFindManyArgs";
import { BellScheduleWhereUniqueInput } from "./BellScheduleWhereUniqueInput";
import { BellScheduleUpdateInput } from "./BellScheduleUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BellScheduleControllerBase {
  constructor(
    protected readonly service: BellScheduleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BellSchedule })
  @nestAccessControl.UseRoles({
    resource: "BellSchedule",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBellSchedule(
    @common.Body() data: BellScheduleCreateInput
  ): Promise<BellSchedule> {
    return await this.service.createBellSchedule({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        numberField: true,
        endTime: true,
        startTime: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BellSchedule] })
  @ApiNestedQuery(BellScheduleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BellSchedule",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async bellSchedules(@common.Req() request: Request): Promise<BellSchedule[]> {
    const args = plainToClass(BellScheduleFindManyArgs, request.query);
    return this.service.bellSchedules({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        numberField: true,
        endTime: true,
        startTime: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BellSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BellSchedule",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async bellSchedule(
    @common.Param() params: BellScheduleWhereUniqueInput
  ): Promise<BellSchedule | null> {
    const result = await this.service.bellSchedule({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        numberField: true,
        endTime: true,
        startTime: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BellSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BellSchedule",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBellSchedule(
    @common.Param() params: BellScheduleWhereUniqueInput,
    @common.Body() data: BellScheduleUpdateInput
  ): Promise<BellSchedule | null> {
    try {
      return await this.service.updateBellSchedule({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          numberField: true,
          endTime: true,
          startTime: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BellSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BellSchedule",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBellSchedule(
    @common.Param() params: BellScheduleWhereUniqueInput
  ): Promise<BellSchedule | null> {
    try {
      return await this.service.deleteBellSchedule({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          numberField: true,
          endTime: true,
          startTime: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
